return {
  "typescript-language-server",
  "css-lsp",
  "html-lsp",
  "json-lsp",
  "lua-language-server",
  "stylua",
  "shellcheck",
  "shfmt",
  "gradle-language-server",
  "groovy-language-server",
  "js-debug-adapter",
  "vim-language-server",
  "markdownlint",
}
